name: CI
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Run ESLint
      run: npx eslint js --ext .js,.jsx,.ts,.tsx